---
baseURL: "https://brandonbohling.com/"
languageCode: "en-us"
title: "Brandon Bohling"
theme: "bohling"
copyright: "&copy; Copyright notice"
permalinks:
  posts: /posts/:slug/
pagination:
  pagerSize: 10

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github-dark

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: snippets
      name: Snippets
      url: https://micro.brandonbohling.com/
      weight: 30
taxonomies:
  category: categories
  tag: tags

params:
  description: "Thoughts on technology, photography, and life from some guy living in the Pacific Northwest."
  author: "Brandon Bohling"
  twitter: "ebohling"
  github: "bbohling"
  linkedin: "brandonbohling"
  vimeo: "ebohling"

services:
  googleAnalytics:
    id: "UA-6588573-1"
