[build]
  publish = "public"
  command = "hugo"

[build.environment]
  # HUGO_VERSION = "0.152.0"
  NETLIFY_BUILD_IMAGE = "ubuntu-22-04"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"  # optional but useful for .GitInfo & lastmod
